In [1]:
import pandas as pd
import numpy as np

In [3]:
cars24 = pd.read_csv('cars24-car-price.csv')
cars24.head()

,full_name,selling_price,year,seller_type,km_driven,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Maruti Alto Std,1.20,2012.0,Individual,120000,Petrol,Manual,19.70,796.0,46.30,5.0
1,Hyundai Grand i10 Asta,5.50,2016.0,Individual,20000,Petrol,Manual,18.90,1197.0,82.00,5.0
2,Hyundai i20 Asta,2.15,2010.0,Individual,60000,Petrol,Manual,17.00,1197.0,80.00,5.0
3,Maruti Alto K10 2010-2014 VXI,2.26,2012.0,Individual,37000,Petrol,Manual,20.92,998.0,67.10,5.0
4,Ford Ecosport 2015-2021 1.5 TDCi Titanium BSIV,5.70,2015.0,Dealer,30000,Diesel,Manual,22.77,1498.0,98.59,5.0

!pip install xgboost

In [14]:
# xgboost for regression on selling price of cars in cars24 dataset
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# use selling price as target variable
y = cars24['selling_price']
X = cars24.drop(['selling_price','full_name'], axis=1)

# Convert categorical columns to type 'category'
categorical_columns = ['seller_type', 'fuel_type', 'transmission_type']
for col in categorical_columns:
    X[col] = X[col].astype('category')

# Create DMatrix with enable_categorical=True
data_dmatrix = xgb.DMatrix(data=X, label=y, enable_categorical=True)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

# Instantiate XGBRegressor
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10, enable_categorical=True)

# Fit xg_reg to training data
xg_reg.fit(X_train, y_train)

# Predict labels of test set
preds = xg_reg.predict(X_test)

# Compute rmse
params = {
    'objective': 'reg:squarederror',
    'colsample_bytree': 0.3,
    'learning_rate': 0.1,
    'max_depth': 5,
    'alpha': 10,
    'n_estimators': 10,
    'enable_categorical': True
}

# cv_results = xgb.cv(dtrain=data_dmatrix, params=params, nfold=3,
#                     num_boost_round=50, early_stopping_rounds=10, metrics="rmse", as_pandas=True, seed=123)

# print(cv_results)
# print((cv_results["test-rmse-mean"]).tail(1))

# Save model to pickle file
import pickle
pickle.dump(xg_reg, open('cars_24.pkl', 'wb'))